user:
  nick: noraesae
  username: noraesae
  realname: noraesae

servers:
  - name: HanIRC
    host: irc.hanirc.org
    encoding: CP949
    nick: 노래새
  - name: Freenode
    host: irc.freenode.net

keys:
  message: ["ㅑ"]
  next-tab: ["ㅎ>ㅅ", "ctrl+tab"]
  previous-tab: ["ㅎ>ㅆ"]
  scroll-down: ["ㅓ"]
  scroll-up: ["ㅏ"]
  scroll-top: ["ㅎ>ㅎ"]
  scroll-bottom: ["shift+ㅎ"]
  page-down: ["ctrl+ㄹ"]
  page-up: ["ctrl+ㅠ"]
