# some default path
path+=$HOME/.dotfiles/scripts

# aliases
alias git='hub'
alias py3='python3'

# exports
export EDITOR='vim'
export TERM='xterm-256color'
export LESS='-R'

# path prepend
path=('/usr/local/bin' $path)
path=('$HOME/.pyenv/shims' $path)

# path append
path+=$HOME/bin
path+=$HOME/.local/bin
path+=$HOME/.stack/programs/x86_64-osx/ghc-8.0.2/bin
path+=./node_modules/.bin
path+=$HOME/.cargo/bin
path+=$HOME/.miniconda3/bin

# Go settings
export GOROOT=$HOME/Works/env/go
export GOPATH=$HOME/Works/go
path+=$GOROOT/bin
path+=$GOPATH/bin

# lang
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'
export LC_CTYPE='en_US.UTF-8'

# history
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=5000
setopt appendhistory
setopt sharehistory
setopt incappendhistory

# zsh-completions
fpath=(/usr/local/share/zsh-completions $fpath)

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# zpresto
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

# disable auto correction
unsetopt correct
unsetopt correct_all

# Conda
conda_path=/anaconda3
__conda_setup="$(CONDA_REPORT_ERRORS=false "$conda_path/bin/conda" shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
  \eval "$__conda_setup"
else
  if [ -f "$conda_path/etc/profile.d/conda.sh" ]; then
    . "$conda_path/etc/profile.d/conda.sh"
    CONDA_CHANGEPS1=false conda activate base
  else
    \export PATH="$conda_path/bin:$PATH"
  fi
fi
unset __conda_setup

# Prompt
PROMPT="%F{8}%2~%f %F{%(?.blue.yellow)}❯%f "
