# some default path
path+=$HOME/.dotfiles/scripts

# aliases
alias vim='nvim'
alias git='hub'
alias em='emacs'

# settings
export EDITOR='nvim'
export TERM='xterm-256color'
export LESS='-R'
export EMACS_TRUE_COLOR_SEPARATOR=';'

# path prepend
path=('/usr/local/bin' $path)
path=('$HOME/.pyenv/shims' $path)

# path append
path+='$HOME/bin'
path+='$HOME/.local/bin'
path+='$HOME/.stack/programs/x86_64-osx/ghc-8.0.2/bin'
path+='./node_modules/.bin'
path+='$HOME/.cargo/bin'

# lang
export LC_ALL='en_US.UTF-8'
export LC_CTYPE='en_US.UTF-8'

# zsh-completions
fpath=(/usr/local/share/zsh-completions $fpath)

# source scripts
source $HOME/.dotfiles/configs/zsh/nvm.sh
source $HOME/.dotfiles/configs/zsh/tmux.sh

# zpresto
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

# theme: sindresorhus/pure
autoload -U promptinit; promptinit
prompt pure
