# some default path
path+=$HOME/.dotfiles/scripts

# aliases
alias py='python'
alias py3='python3'

# exports
export EDITOR='vim'
export TERM='xterm-256color'
export LESS='-R'

# path prepend
path=('/usr/local/bin' $path)
path=('$HOME/.pyenv/shims' $path)

# path append
path+=$HOME/bin
path+=$HOME/.local/bin
path+=./node_modules/.bin
path+=$HOME/.cargo/bin

# Go settings
export GOPATH=$HOME/Works/gopath
path+=$GOPATH/bin

# Flutter
FLUTTER_PATH=$HOME/Works/env/flutter/bin
path+=$FLUTTER_PATH

# lang
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'
export LC_CTYPE='en_US.UTF-8'

# history
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=5000
setopt appendhistory
setopt sharehistory
setopt incappendhistory

# zsh-completions
fpath=(/usr/local/share/zsh-completions $fpath)

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# zpresto
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

# zsh-syntax-highlighting
export ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern line root)

# disable auto correction
unsetopt correct
unsetopt correct_all

# Prompt
PROMPT="%F{8}%2~%f %F{%(?.blue.yellow)}#%f "

# Conda
eval "$("$HOME/miniconda3/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"

# Cuda
CUDA=/usr/local/cuda-11.7
if [ -d "$CUDA" ];
then
  path+=$CUDA/bin
  export LD_LIBRARY_PATH=$CUDA/lib64:$LD_LIBRARY_PATH
fi
