#!/usr/bin/env bash

editorconfig=$(cat <<EOF
root = true

[*]
charset = utf-8
end_of_line = lf
indent_size = 2
indent_style = space
insert_final_newline = true
EOF
)

echo "$editorconfig" > .editorconfig
