#!/bin/sh

git filter-branch --tag-name-filter cat --env-filter '

an="$GIT_AUTHOR_NAME"
am="$GIT_AUTHOR_EMAIL"
cn="$GIT_COMMITTER_NAME"
cm="$GIT_COMMITTER_EMAIL"

if [ "$GIT_COMMITTER_EMAIL" = "noraesae@yuiazu.net" ]
then
    cn="Hyunje Alex Jun"
    cm="me@noraesae.net"
fi
if [ "$GIT_AUTHOR_EMAIL" = "noraesae@yuiazu.net" ]
then
    an="Hyunje Alex Jun"
    am="me@noraesae.net"
fi
if [ "$GIT_COMMITTER_EMAIL" = "me@noraesae.net" ]
then
    cn="Hyunje Alex Jun"
    cm="me@noraesae.net"
fi
if [ "$GIT_AUTHOR_EMAIL" = "me@noraesae.net" ]
then
    an="Hyunje Alex Jun"
    am="me@noraesae.net"
fi

export GIT_AUTHOR_NAME="$an"
export GIT_AUTHOR_EMAIL="$am"
export GIT_COMMITTER_NAME="$cn"
export GIT_COMMITTER_EMAIL="$cm"
'
