#!/usr/bin/env python
import requests
import time
import os

while True:
    try:
        if "NAVER" in requests.get("http://www.naver.com").text:
            print 'Success!'
            os.system("open http://google.com")
            break
        else:
            print 'Failed!'
            time.sleep(1)
    except:
        time.sleep(1)
