#!/usr/bin/env python
import os
import subprocess
import sys


def main():
    if len(sys.argv) == 1:
        return

    process_name = sys.argv[1]

    search_name = '[' + process_name[0] + ']' + process_name[1:]
    current_pid = os.getpid()
    p = subprocess.Popen("echo $(ps aux | grep '" + search_name + "' | awk '{print $2}')", stdout=subprocess.PIPE, shell=True)
    out, err = p.communicate()
    for pid in out.split():
        if pid != str(current_pid):
            print "Killing " + process_name + ":" + pid
            os.system("kill " + pid)

if __name__ == "__main__":
    main()
