#!/usr/bin/env bash

if [ -z "$3" ]; then
  scale=600
else
  scale=$3
fi

palette="/tmp/palette.png"

filters="fps=15,scale=$scale:-1:flags=lanczos"

ffmpeg -v warning -i $1 -vf "$filters,palettegen" -y $palette
ffmpeg -v warning -i $1 -i $palette -lavfi "$filters [x]; [x][1:v] paletteuse" -y $2
